from dataclasses import field

from pydantic.dataclasses import dataclass

from cave.resource import Grant


@dataclass
class APIResourceConfiguration:
    """Configuration for the PostgREST API resource.

    Controls the schema and privileges for the API view
    generated by a dimension factory.
    """

    schema_name: str = "api"
    grants: list[Grant] = field(default_factory=lambda: ["select"])


@dataclass
class DimensionConfiguration:
    """Configuration for dimension table factories."""

    id_field_name: str = "id"
