"""aol

Revision ID: 9391943cc124
Revises:
Create Date: 2026-03-10 17:57:18.397598

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9391943cc124"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS private")
    op.create_table(
        "students",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="private",
    )
    op.create_table(
        "students_attributes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="private",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users", schema="public")
    op.drop_table("students_attributes", schema="private")
    op.drop_table("students", schema="private")
    op.execute("DROP SCHEMA IF EXISTS private")
    # ### end Alembic commands ###
